#!/usr/bin/env python3
import darkweb
import os
import reportgenerator
import animations
import googledork

RESET = "\033[0m"
BLACK = "\033[0;30m"
RED = "\033[0;31m"
GREEN = "\033[0;32m"
YELLOW = "\033[0;33m"
BLUE = "\033[0;34m"
PURPLE = "\033[0;35m"
CYAN = "\033[0;36m"
WHITE = "\033[0;37m"
BOLD_BLACK = "\033[1;30m"
BOLD_RED = "\033[1;31m"
BOLD_GREEN = "\033[1;32m"
BOLD_YELLOW = "\033[1;33m"
BOLD_BLUE = "\033[1;34m"
BOLD_PURPLE = "\033[1;35m"
BOLD_CYAN = "\033[1;36m"
BOLD_WHITE = "\033[1;37m"
UNDERLINE_BLACK = "\033[4;30m"
UNDERLINE_RED = "\033[4;31m"
UNDERLINE_GREEN = "\033[4;32m"
UNDERLINE_YELLOW = "\033[4;33m"
UNDERLINE_BLUE = "\033[4;34m"
UNDERLINE_PURPLE = "\033[4;35m"
UNDERLINE_CYAN = "\033[4;36m"
UNDERLINE_WHITE = "\033[4;37m"
BACKGROUND_BLACK = "\033[40m"
BACKGROUND_RED = "\033[41m"
BACKGROUND_GREEN = "\033[42m"
BACKGROUND_YELLOW = "\033[43m"
BACKGROUND_BLUE = "\033[44m"
BACKGROUND_PURPLE = "\033[45m"
BACKGROUND_CYAN = "\033[46m"
BACKGROUND_WHITE = "\033[47m"

logo = f'''{CYAN}_______ _____________________   __________{RESET}
{RED}__  __ \__  ___/____  _/___  | / /___  __/{RESET}
{BLUE}_  / / /_____ \  __  /  __   |/ / __  /{RESET}
{PURPLE}/ /_/ / ____/ / __/ /   _  /|  /  _  /{RESET}
{RED}\____/  /____/  /___/   /_/ |_/   /_/{RESET}
'''

animations.animatetext(logo, 1)
animations.animatetext(f"\t        {RED}[+]By Yohannes Samuel{RESET}\n\n", 2)

results = {"dork": "", "darkweb": ""}

animations.animatetext(f"{YELLOW}[+] Scraping For Identity\n", 1)
name = str(input(f"[+] Enter a name: {RESET}"))
results["dork"] = googledork.main(name)
darkwebresults = darkweb.main(name)
results["darkweb"] = darkwebresults
print(results["darkweb"])
reportgenerator.generate_report(results)
animations.animatetext("\n\n[+] Finished writting report, Thanks for using!", 2)

